# -*- coding: utf-8 -*-
"""UTS PBO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9tHth3KnpY2KEnogPzdq79X6T8yoqUP
"""

# Class User (induk)
class Pengguna:
    def __init__(self, nama, role):
        self.nama = nama
        self.role = role

    def login(self):
        return f"{self.nama} berhasil login sebagai {self.role}"


# Class turunan
class Admin(Pengguna):
    def akses_dashboard(self):
        return "Admin mengakses dashboard dan mengelola data pengunjung"

    def konfirmasi_pembayaran(self):
        return "Admin mengkonfirmasi status pembayaran tiket"


class User(Pengguna):
    def input_data(self):
        return "User menginput data pemesanan tiket"

    def lihat_status(self):
        return "User melihat cuaca dan map bromo"


# Contoh penggunaan
admin = Admin("AdminBromo", "admin")
user = User("Chelsea", "user")

print(admin.login())
print(admin.akses_dashboard())
print(admin.konfirmasi_pembayaran())

print(user.login())
print(user.input_data())
print(user.lihat_status())

# Class induk
class PaketWisata:
    def hitung(self, jumlah):
        return f"Total pengunjung: {jumlah} orang"


# Class turunan (override method)
class PaketLengkapBromo(PaketWisata):
    def hitung(self, jumlah):
        return f"Paket Lengkap Bromo - {jumlah} orang"


class PaketSunrise(PaketWisata):
    def hitung(self, jumlah):
        return f"Paket Sunrise Penanjakan - {jumlah} orang"


class PaketPrivateTrip(PaketWisata):
    def hitung(self, jumlah):
        return f"Paket Private Trip - {jumlah} orang"


# Contoh data sesuai tabel kamu
data_pengunjung = [
    (PaketLengkapBromo(), 5),
    (PaketSunrise(), 2),
    (PaketSunrise(), 4)
]

# Menjalankan polymorphism
for paket, jumlah in data_pengunjung:
    print(paket.hitung(jumlah))

class Pengunjung:
    def __init__(self, nama, jumlah):
        self.__nama = nama
        self.__jumlah = jumlah

    def get_data(self):
        return f"{self.__nama} - {self.__jumlah} orang"

    def set_jumlah(self, jumlah):
        if jumlah > 0:
            self.__jumlah = jumlah

class Pengunjung:
    def __init__(self, nama, jumlah):
        self.__nama = nama
        self.__jumlah = jumlah

    def get_data(self):
        return f"{self.__nama} - {self.__jumlah} orang"

    def set_jumlah(self, jumlah):
        if jumlah > 0:
            self.__jumlah = jumlah


p = Pengunjung("Chelsea", 5)

print(p.get_data())   # tampilkan data

p.set_jumlah(10)

print(p.get_data())   # setelah diubah