# -*- coding: utf-8 -*-
"""PBO pertemuan 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZnYoosZMeioNcLvRpM7GS68sUaICKbj
"""

def tambah (a, b) :
  return a + b

print(tambah(2, 3))
print(tambah("Hello ", "AI"))

def kali (a, b) :
  return a * b

print(tambah(3, 5))
print(tambah("Hello ",  "3"))

#latihan 1
class Kendaraan:
  def berjalan(selft):
    print("Kendaraan sedang berjalan")

class Mobil(Kendaraan):
    def berjalan(self):
        print("Mobil berjalan di jalan raya")

class Motor(Kendaraan):
    def berjalan(self):
        print("Motor melaju di jalan raya ")

class Pesawat(Kendaraan):
    def berjalan(self):
        print("Pesawat terbang di udara ")

daftar_kendaraan = [
    Mobil(),
    Motor(),
    Pesawat()
]

for kendaraan in daftar_kendaraan:
    kendaraan.berjalan()

#latihan 2
class Kendaraan:
  def __init__(self, kecepatan):
        self.kecepatan = kecepatan

  def berjalan(selft):
    print(f"Kendaraan sedang berjalan {self.kecepatan} km/jam")

class Mobil(Kendaraan):
    def berjalan(self):
        print(f"Mobil berjalan di jalan raya {self.kecepatan} km/jam")

class Motor(Kendaraan):
    def berjalan(self):
        print(f"Motor melaju di jalan raya {self.kecepatan} km/jam")

class Pesawat(Kendaraan):
    def berjalan(self):
        print(f"Pesawat terbang di udara {self.kecepatan} km/jam")

class kapal(Kendaraan):
  def berjalan(self):
      print(f"Kapal berlayar ke laut {self.kecepatan} km/jam")

daftar_kendaraan = [
    Mobil(120),
    Motor(80),
    Pesawat(56),
    kapal(100)
]

for kendaraan in daftar_kendaraan:
    kendaraan.berjalan()

# Parent class
class Karyawan:
    def __init__(self, nama):
        self.nama = nama

    def hitung_gaji(self):
        pass

    def gaji_bersih(self):
        gaji_kotor, _ = self.hitung_gaji()  # ambil gaji kotor dari tuple

        # Potongan pajak jika gaji > 5 juta
        if gaji_kotor > 5000000:
            pajak = 0.05 * gaji_kotor
        else:
            pajak = 0

        return gaji_kotor - pajak, pajak


# Child class: Karyawan Tetap
class KaryawanTetap(Karyawan):
    def __init__(self, nama, gaji_bulanan):
        super().__init__(nama)
        self.gaji_bulanan = gaji_bulanan

    def hitung_gaji(self):
        # Bonus 10%
        bonus = 0.10 * self.gaji_bulanan
        gaji_kotor = self.gaji_bulanan + bonus
        return gaji_kotor, bonus


# Child class: Karyawan Freelance
class KaryawanFreelance(Karyawan):
    def __init__(self, nama, jam_kerja, tarif_per_jam):
        super().__init__(nama)
        self.jam_kerja = jam_kerja
        self.tarif_per_jam = tarif_per_jam

    def hitung_gaji(self):
        gaji_kotor = self.jam_kerja * self.tarif_per_jam
        return gaji_kotor, 0  # Freelance tidak ada bonus


# Data karyawan (polimorfisme)
daftar_karyawan = [
    KaryawanTetap("Andi", 5000000),
    KaryawanFreelance("Budi", 100, 20000),
    KaryawanTetap("Citra", 7000000),
    KaryawanFreelance("Dewi", 80, 25000)
]


# Output
for karyawan in daftar_karyawan:
    gaji_kotor, bonus = karyawan.hitung_gaji()
    gaji_bersih, pajak = karyawan.gaji_bersih()

    print(f"Nama: {karyawan.nama}")
    print(f"Gaji Kotor: {gaji_kotor}")
    print(f"Bonus: {bonus}")
    print(f"Pajak: {pajak}")
    print(f"Gaji Bersih: {gaji_bersih}")
    print("-" * 30)

from datetime import datetime
class Barang:
    def __init__(self, id_barang, nama, harga):
        self.id_barang = id_barang
        self.nama = nama
        self.harga = harga

    def info(self):
        return f"[{self.id_barang}] {self.nama:18} | Rp{self.harga:10,}"

    def to_dict(self):
        return {"tipe": "umum", "id": self.id_barang, "nama": self.nama, "harga": self.harga}


class BarangElektronik(Barang):
    def __init__(self, id_barang, nama, harga, garansi):
        super().__init__(id_barang, nama, harga)
        self.garansi = garansi

    def info(self):
        return f"{super().info()} | Garansi: {self.garansi} bln"

    def to_dict(self):
        d = super().to_dict()
        d.update({"tipe": "elektronik", "garansi": self.garansi})
        return d


class BarangKonsumsi(Barang):
    def __init__(self, id_barang, nama, harga, tgl_exp):
        super().__init__(id_barang, nama, harga)
        self.tgl_exp = tgl_exp

    def info(self):

        exp_date = datetime.strptime(self.tgl_exp, "%Y-%m-%d").date()
        today = datetime.today().date()

        status = "MASIH BERLAKU"
        if today > exp_date:
            status = "KADALUARSA!"

        return f"{super().info()} | Exp: {self.tgl_exp} ({status})"

    def to_dict(self):
        d = super().to_dict()
        d.update({"tipe": "konsumsi", "tgl_exp": self.tgl_exp})
        return d


import json
import os

class GudangPolimorfik:
    def __init__(self, file_db='gudang_v3.json'):
        self.file_db = file_db
        self.koleksi = []
        self.muat_data()

    def tambah_barang(self, objek_barang):
        self.koleksi.append(objek_barang)
        self.simpan_data()

    def simpan_data(self):
        with open(self.file_db, 'w') as f:
            data = [b.to_dict() for b in self.koleksi]
            json.dump(data, f, indent=4)

    def muat_data(self):
        if os.path.exists(self.file_db):
            with open(self.file_db, 'r') as f:
                data_list = json.load(f)
                self.koleksi = []
                for d in data_list:
                    if d['tipe'] == "elektronik":
                        obj = BarangElektronik(d['id'], d['nama'], d['harga'], d['garansi'])
                    elif d['tipe'] == "konsumsi":
                        obj = BarangKonsumsi(d['id'], d['nama'], d['harga'], d['tgl_exp'])
                    else:
                        obj = Barang(d['id'], d['nama'], d['harga'])
                    self.koleksi.append(obj)

    def laporan_stok(self):
        print("\n" + "="*70)
        print(f"{'ID':6} | {'NAMA BARANG':18} | {'HARGA':13} | {'KETERANGAN TAMBAHAN'}")
        print("-"*70)
        for b in self.koleksi:
            print(b.info())
        print("="*70)

def main():
    app = GudangPolimorfik()

    if not app.koleksi:
        print("Database kosong, membuat data awal...")
        app.tambah_barang(BarangElektronik("E01", "Laptop Pro", 12000000, 12))
        app.tambah_barang(BarangKonsumsi("K02", "Roti Coklat", 15000, "2026-05-10"))
        app.tambah_barang(Barang("U03", "Kabel Data", 25000))

    app.laporan_stok()


if __name__ == "__main__":
    main()

from datetime import datetime

# Parent Class
class Barang:
    def __init__(self, nama):
      self.nama = nama

    def info(self):
      pass

# Child Class: Barang Konsumsi dengam Validasi Kadaluarsa
class BarangKonsumsi(Barang):
    def __init__(self, nama, tanggal_kadaluarsa):
      super().__init__(nama)
      #Format tanggal: YYYY-MM-DD
      self.tanggal_kadaluarsa = datetime.strptime(tanggal_kadaluarsa, "%Y-%m-%d")

    def info(self):
    # Mendapatkan waktu sistem saat ini
      hari_ini = datetime.now()

    # Logika pengecekan kadaluarsa
      if hari_ini > self.tanggal_kadaluarsa:
          status = "SUDAH KADALUARSA"
      else:
          status = "MASIH LAYAK KONSUMSI"

      print(f"Nama Barang : {self.nama}")
      print(f"Expired Date: {self.tanggal_kadaluarsa.strftime('%d-%m-%Y')}")
      print(f"Status      : {status}")

# Data Barang
daftar_barang = [
    BarangKonsumsi("Susu Kotak", "2023-01-01"), # Contoh sudah lewat
    BarangKonsumsi("Roti Tawar", "2026-12-31"), # Contoh masih lama
    BarangKonsumsi("Mie Instan", "2024-05-20")  # Contoh tanggal laimnya
]

# Output (Polimorfisme)
print("Validasi Stok Barang Konsumsi\n")
for barang in daftar_barang:
  barang.info()
  print("-" * 35)